### ISSUE TITLE
Need help gettting this working pls?

### ISSUE THREAD

**Issue by adamgins** [jwohlfert23/react-native-tag-input#24]
Hi trying to get this working but seem to be struggling, any help appreciated:

```
                        <TagInput
                            value={['one', 'two']}
                            onChange={(emails) => this.onEmailChange(emails)} 
                        
                        />
```

the onEmailChange just has a console.log:

```
 onEmailChange (emails){
        console.log(emails);
    }
```

I get the following rendered:

![screen shot 2017-02-03 at 4 23 30 pm](https://cloud.githubusercontent.com/assets/7233741/22582694/66077fa4-ea3c-11e6-8516-b105413ffd57.png)

I have a few issues:
1) When I click `one` console log renders `two` 
2) typing in the type somehting field where I have `ssssas` seems to have no impact whatssoever.

Any help appreciated

thanks

**Comment by sidutta** [comment]
I'm facing the same issue too.

**Comment by sidutta** [comment]
For anyone else who encounters this problem, this happens because the version available through npm is not the same the one here on git. 

> const regex = this.props.regex || /([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9._-]+)/gi;

is the check in the npm code. Thus, only email addresses are accepted as valid tags.

**Comment by jwohlfert23** [comment]
I'll publish the latest version right now. Sorry about that.

**Comment by jwohlfert23** [comment]
Try now.

**Comment by sidutta** [comment]
Yes, it's working fine now. Thanks!
