### ISSUE TITLE
On Android after adding a tag it scrolls out of sight

### ISSUE THREAD

**Issue by corymsmith** [jwohlfert23/react-native-tag-input#25]
Wondering if this is due to the height I have set on the container? What would be the ideal styles to use so that this doesn't happen?

**Comment by Balderious** [comment]
I agree with @corymsmith . This functionality is very interesting but the display problem on Android makes it unusable. Or there is simply a lack of documentation.

**Comment by sinewave440hz** [comment]
See also https://github.com/jwohlfert23/react-native-tag-input/issues/34

**Comment by gvillenave** [comment]
#41 should help.
