### ISSUE TITLE
Autofocus

### ISSUE THREAD

**Issue by natestraub** [jwohlfert23/react-native-tag-input#3]
Hi there!

Hoping you could help me out with figuring out the autofocus on this when opening inside a modal.  I've tried adding both "autofocus: {true}" as a prop and also trying to give the actual control a ref and then using this.refs.emailInput.focus() but can't seem to get either to work.  Any help would be appreciated.

Thanks!

**Comment by jwohlfert23** [comment]
Working on an update now that should allow you to add the autofocus attribute.

**Comment by jwohlfert23** [comment]
You can add `inputProps={{autoFocus:true}}` as a prop and that should work.
