### ISSUE TITLE
 All tags in a single line, no vertical scrolling

### ISSUE THREAD

**Issue by lenoxzzedwin** [jwohlfert23/react-native-tag-input#34]
`<TagInput>`

Tags positioned above
Cursor positioned in  new line

![image](https://user-images.githubusercontent.com/16271405/27265501-b3151c40-545c-11e7-8c49-1ef20622996a.png)

`<Input>`
"Tags" in position Left 
Cursor positioned on a single line

I WANT THIS

![image](https://user-images.githubusercontent.com/16271405/27266027-d114e0e4-5462-11e7-8f43-ee5200c65926.png)

**Comment by sinewave440hz** [comment]
That's how it works on iOS but, as you illustrate, not an Android :/ Should of course be the same on both...

**Comment by jamesone** [comment]
Did you play around with:

• maxHeight 
• scrollViewProps
> You should be able to turn the scrollview into a horizontal scrollview (you can do this with react-native - https://facebook.github.io/react-native/docs/scrollview.html)

**Comment by Ashoat** [comment]
This can be done now, see the [example project](https://github.com/jwohlfert23/react-native-tag-input/blob/master/Example/src/TagInputExample.js)
