### ISSUE TITLE
TextInput props

### ISSUE THREAD

**Issue by darrenfurr** [jwohlfert23/react-native-tag-input#4]
Great work on this tag input. Since it essentially extends a TextInput - any reason you don't allow us to pass in any property of a TextInput? 

<TextInput
props={...props}

Specifically, I'm looking to change the selectionColor prop of the TextInput.

Thanks,
-Darren

**Comment by jwohlfert23** [comment]
Working on an update for this now. Thanks for the suggestion.

**Comment by jwohlfert23** [comment]
This has been added.
