### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by vvavepacket** [jwohlfert23/react-native-tag-input#49]
Does this plugin support auto complete of tags? If not, what would be the best approach to complement this plugin with that feature? Thank you.

**Comment by Ashoat** [comment]
Yes, it’s a fully controlled component, just set the properties to what you want.

**Comment by vvavepacket** [comment]
Im not seeing the property to set auto completion :(

**Comment by Ashoat** [comment]
There is no single magical property to set "auto completion". However, as TagInput is a fully controlled component, it should be possible to implement whatever UI you need that requires a TagInput.

I've implemented what I call a "typeahead" but I suppose might be "auto completion" to you [here](native/chat/settings/add-users-modal.react.js). Give that code a read if you're confused. If you're still confused, please try reading the code of this component to learn more.

I unfortunately don't have time to help you more, and won't be able to respond to this issue again. Good luck! I'm confident you can figure it out.

(By the way, in the future please include a lot more detail. "Auto completion" means one thing to one person and another thing to another person.)
