### ISSUE TITLE
Warning when updating values

### ISSUE THREAD

**Issue by henriquesantiago** [jwohlfert23/react-native-tag-input#5]
When I try to update the values (with the onChange handler), I get this warning and no visual changes to the input component:

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the  component.

I do get an array with the new elements, though. The issue arises when I try to execute any setState operation inside the function called by onChange.

Also, I tried to see if the component really unmounted with the componentWillUnmount method, but it doesn't get executed at all. Any suggestions as to why I'm getting this warning?

**Comment by jwohlfert23** [comment]
Can you post your code? Happy to debug with you.
