### ISSUE TITLE
IDE code highlighting

### ISSUE THREAD

**Issue by joe-lloyd** [jwohlfert23/react-native-tag-input#51]
When I installed your library in my project the react native code highlighting becomes undefined. 

The IDE I use is PhpStorm & WebStorm. This library makes the components from react native become undefined and have no highlighting or code completion in the IDE.

**Comment by Ashoat** [comment]
Sorry, but that definitely seems like an IDE issue. No library should be able to break code highlighting. I’m not sure why this is happening, as I don’t use the aforementioned IDE and don’t believe we have any configs in the repo for that IDE. I unfortunately do not have time to investigate this issue further, sorry!

**Comment by joe-lloyd** [comment]
Its definitely the library & of course a library can break code highlighting if it's indexed from the node_modules.
Probably something to do with the way you include react or flow. 
Anyway I thought I would flag the issue incase someone else has this problem with your library.
