### ISSUE TITLE
Which minimum React / React Native versions is supported ?

### ISSUE THREAD

**Issue by louisiscoding** [jwohlfert23/react-native-tag-input#52]
I'm using react-native in its 0.42.3 version due to the specifity of my project.
I'm having trouble with this library. (ViewPropTypes.style is undefined)

I'd like to know from which version this component is fully supported.

Great job,
Thanks

**Comment by Ashoat** [comment]
I think we support version 49 and 48, but I’m not sure, as I only ever test with the latest version (51 now I think?).
