### ISSUE TITLE
Override 'x'

### ISSUE THREAD

**Issue by cawfree** [jwohlfert23/react-native-tag-input#53]
Hi, thanks for this very awesome Component!

I was wondering, would it be possible to override the 'delete' option on tags, both graphically (i.e. render a custom character/`<View>`) and functionally (`onTagPressed={ (tag) => { } }`)?

**Comment by Ashoat** [comment]
No I don't believe so, but would welcome a PR!

**Comment by maharjanaman** [comment]
@Ashoat is there way to remove close icons from non editable tags???

**Comment by Ashoat** [comment]
Not currently.
