### ISSUE TITLE
Example code: can't add more than one tag?

### ISSUE THREAD

**Issue by choiRyan** [jwohlfert23/react-native-tag-input#55]
React native v0.54: The error actually seems to stem from https://github.com/facebook/react-native/issues/18374 . Didn't know whether to keep this issue open here.

**Comment by nol13** [comment]
https://github.com/facebook/react-native/pull/19087
+
https://github.com/facebook/react-native/pull/18627

both of these together seem to take care of it for me, if you feel like running a forked RN version until patch is merged.
