### ISSUE TITLE
Getting Cannot resolve symbol 'React-Native-Component'

### ISSUE THREAD

**Issue by theapache64** [jwohlfert23/react-native-tag-input#62]
When i include this library in my project, Webstorm says `Cannot resolve symbol 'React-Native-Component'` where React-Native-Component = any react native component. 

![image](https://user-images.githubusercontent.com/9678279/40231073-510303c0-5ab7-11e8-90c5-d7936a165445.png)

**Comment by Ashoat** [comment]
I'm not familiar with Webstorm and I'm not sure why Webstorm would do that. I can't imagine what that error would have to do with this library.

**Comment by theapache64** [comment]
I've deleted `flow-typed` folder from `node_modules/react-native-tag-input` and the error gone. I am new in RN. I don't know why it worked. I think it happened due to the collision of multiple version of react native.

**Comment by Ashoat** [comment]
That's helpful to know. We shouldn't be including that folder in the package anyways. I'll put out a new version in a second that doesn't include that folder.

**Comment by theapache64** [comment]
Okay. that's great. Btw, the library is awesome. :+1:

**Comment by sibelius** [comment]
this is not a problem with this package at all

we should close this

**Comment by theapache64** [comment]
I think it's a problem with the package, and @Ashoat told me that there will be a new version with a fix to this issue. Anyways, am closing this. Tnx all for the response.

**Comment by Ashoat** [comment]
`react-native-tag-input@0.0.20` has just been published and it should not include `flow-typed`.

**Comment by theapache64** [comment]
Updated (y). Tnx @Ashoat :) 

![image](https://user-images.githubusercontent.com/9678279/40244201-dd233fb4-5adf-11e8-8658-a8916ffd581f.png)
