### ISSUE TITLE
FEATURE REQ: Allow spaces inside the Tags?

### ISSUE THREAD

**Issue by jamesone** [jwohlfert23/react-native-tag-input#68]
Is this feature already here? (I couldn't find it)

If not, is it possible that this feature could be added? Are there any limitations that's preventing this feature from being implemented on Android or IOS?

**Comment by Ashoat** [comment]
This is a fully controlled component, so it's actually up to you to determine what is or isn't allowed in the tags. Whenever the input text changes, the `onChangeText` callback property will get called. It's up to you to mutate the `value` property (which contains the list of tags) based on the updated text, so you could simply choose not to add new entries to the `value` array when spaces are added.

**Comment by sam9010** [comment]
can you give me example?
