### ISSUE TITLE
Input box not getting emptied in a proper manner

### ISSUE THREAD

**Issue by charanrajh** [jwohlfert23/react-native-tag-input#74]
After entering so many tags, I started to clear them one by one. Even though I cleared all of them, the placeholder text "search" is located at the center and after pressing the clear button twice or thrice , it is coming to the start.
![screenshot_20190214-133005](https://user-images.githubusercontent.com/37415880/52771847-02e27c80-305d-11e9-90ad-5080f2d781db.png)
![screenshot_20190214-132956](https://user-images.githubusercontent.com/37415880/52771876-20afe180-305d-11e9-9b76-7d6ec2b9a46a.png)

**Comment by Ashoat** [comment]
I can investigate further if you can provide an [MCVE](https://stackoverflow.com/help/mcve) that reproduces the issue, in the form of an [Expo Snack](https://snack.expo.io/) or a `react-native init`'d repo hosted on GitHub.
