### ISSUE TITLE
I would like to ask God, there is no content, press the blank space will produce empty Tags how to solve?

### ISSUE THREAD

**Issue by KenPanda** [jwohlfert23/react-native-tag-input#75]
I would like to ask God, there is no content, press the blank space will produce empty Tags how to solve?

**Comment by Ashoat** [comment]
I have no idea what you're asking.

**Comment by ya-watanabe** [comment]
how about to set height/width state to scrollview props? it solves in my case.

**Comment by ConnectedReasoning** [comment]
God is a coder, I knew it!
