### ISSUE TITLE
Nothing is drawn on Android

### ISSUE THREAD

**Issue by erm100** [jwohlfert23/react-native-tag-input#76]
Nothing is drawn when I use TagInput. My code:
```
  export class TagsInput extends Component {

    constructor(props) {
      super(props);
      this.state = {
        text: "tags",
        tags: ["tags_1", "tags_2", "tags_3"],
        tag: ""
      }
    }

    render() {
      return (
        <TagInput
          value={this.state.tags}
          onChange={(tags) => this.setState({ tags })}
          labelExtractor={(tag) => tag}
          text={this.state.text}
          onChangeText={(text) => this.setState({ text })}
        />
      );
    }

  }
}
```
Are there any design requirements for TagInput? What are the requirement for the styles?

**Comment by mohanprasathsj** [comment]
Same issue here aswell. Nothing getting displayed in Android.

**Comment by Ashoat** [comment]
1. Why are you using different state variables for the `text` and `onChangeText` properties?
2. `onChangeText` should have the capacity to append values to the `tags` state variable
3. If after addressing these issues you are still having problems, you’ll need to provide an [MCVE](https://stackoverflow.com/help/mcve) that reproduces what you're seeing, in the form of an [Expo Snack](https://snack.expo.io/) or a `react-native init`'d repo hosted on GitHub

**Comment by erm100** [comment]
Everything works correctly.
