### ISSUE TITLE
How to hide cursor 

### ISSUE THREAD

**Issue by gauravsbagul** [jwohlfert23/react-native-tag-input#81]
I am using my custom input box to enter keywords, and I don't want to show the cursor comes after tags. and when I do editable= false, I am not able to delete tags so is there any other way to hide the cursor and still able to delete tags.

![image_2020_01_02T07_45_13_444Z](https://user-images.githubusercontent.com/25247251/71656638-ff81dd80-2d61-11ea-965e-df196a37e5a8.png)

**Comment by Ashoat** [comment]
No, sorry, this isn't currently possible. This component is set up to have the `TextInput` flow inline after the list of selected tags. I'd suggest forking or copying some of the code in this project in order to spin your own solution, keeping in mind the license requirements.
