### ISSUE TITLE
Done key not adding a tag

### ISSUE THREAD

**Issue by ingeniousgenius** [jwohlfert23/react-native-tag-input#82]
Hey, first of all thanks for the library.

I just finished installing it and I can't find a way to add any new tags from the input; pressing the return key on the keyboard does nothing and neither does using space or a comma or anything.

I think the ReadMe.md should indicate how this is supposed to work, mabye visually or written to make it easier to understand.

Apologies if this issue is repetitive.

**Comment by Ashoat** [comment]
This is a controlled component. It's the user's job to update the list of tags, which is passed in via the `value` prop. If you ever find yourself confused about how to use a package, try to search for examples, either in the repo or elsewhere on GitHub. Here is a [link to the example usage](https://github.com/jwohlfert23/react-native-tag-input/blob/master/Example/src/TagInputExample.js#L46-L58) in the repo.
